## **THỰC HÀNH: CÁC GIẢI THUẬT PHÂN LOẠI CƠ BẢN**

### **2.3. GIẢI THUẬT 3: BAYES NGÂY THƠ (NAÏVE BAYES)**

#### **2.3.1. Ôn tập lý thuyết**

##### ***Giải thuật Naive Bayes hoạt động như thế nào? Hãy giải thích định lý Bayes và giả định "ngây thơ" trong thuật toán này?***

Naive Bayes là một thuật toán học có giám sát dùng để giải quyết cho các bài toán phân loại, hoạt động dựa trên Định lý Bayes. Đây là một bộ phân loại xác suất, trong đó thuật toán học cách ước lượng xác suất xuất hiện của từng đặc điểm trong mỗi lớp. Khi dự đoán, thuật toán sẽ kết hợp các xác suất này và gán đối tượng vào lớp có xác suất cao nhất.

Định lý Bayes mô tả cách tính xác suất của một giả thuyết dựa trên bằng chứng quan sát được. Nó kết hợp giữa xác suất tiên nghiệm của giả thuyết P(H) và xác suất quan sát bằng chứng khi giả thuyết đúng P(E|H) để suy ra xác suất hậu nghiệm của giả thuyết khi đã có bằng chứng P(H|E). Công thức được viết là:

                                        P(H|E) = (P(E|H) * P(H))/P(E)
- P(H) là xác suất tiên nghiệm của giả thuyết H; 
- P(E|H) là xác suất xảy ra bằng chứng E khi H đúng;
- P(E) là xác suất xảy ra bằng chứng E; 
- P(H|E) là xác suất hậu nghiệm cần tìm.
  
Trong thuật toán Naive Bayes, công thức này được sử dụng để tính xác suất một đối tượng thuộc về từng lớp dựa trên các đặc điểm quan sát, sau đó chọn lớp có xác suất cao nhất.

Giả định “ngây thơ” của thuật toán là các đặc điểm dữ liệu là độc lập có điều kiện khi biết lớp. Nhờ vậy, ta có thể viết P(E|H) dưới dạng tích của các xác suất thành phần, giúp việc tính toán đơn giản hơn nhiều so với việc ước lượng toàn bộ phân phối phức tạp của dữ liệu. Mặc dù giả định này hiếm khi đúng hoàn toàn trong thực tế nhưng nó vẫn cho phép Naive Bayes hoạt động hiệu quả và được ứng dụng rộng rãi trong nhiều bài toán phân loại, đặc biệt là xử lý văn bản và lọc thư rác.

##### ***Các loại mô hình Naive Bayes (Gaussian, Multinomial, Bernoulli) khác nhau ra sao? Khi nào nên sử dụngtừng loại?***

**Gaussian Naive Bayes:**
- Gaussian Naive Bayes được sử dụng khi các thuộc tính của dữ liệu là biến liên tục và giả định rằng trong từng lớp, các biến này tuân theo phân phối Gaussian (hay phân phối chuẩn). Với giả định này, mô hình có thể ước lượng xác suất một cách đơn giản và nhanh chóng mà không cần đến các phép tính phức tạp. Đây là một thuật toán đơn giản nhưng hiệu quả, đặc biệt giúp tăng tốc độ huấn luyện và dự đoán. Trong nhiều tình huống, sai số của Gaussian Naive Bayes chỉ lớn gấp đôi so với Naive Bayes tối ưu, do đó nó vẫn được xem là một lựa chọn thực tế và đáng tin cậy cho dữ liệu liên tục.
- Mô hình này thường được áp dụng trong các bài toán có dữ liệu đo lường, dữ liệu y sinh, phân loại tín dụng,… hoặc các dữ liệu dạng số thực như chiều cao, cân nặng, điểm số hay nhiệt độ.

**Multinomial Naive Bayes:**
- Multinomial Naive Bayes được sử dụng khi các thuộc tính của dữ liệu là rời rạc và biểu diễn dưới dạng tần suất hoặc số lần xuất hiện của sự kiện (giá trị nguyên không âm). Mô hình cho phép ước lượng xác suất một đối tượng thuộc về từng lớp dựa trên phân phối tần suất của các đặc trưng.
- Loại mô hình này đặc biệt phù hợp trong các bài toán phân loại văn bản, nơi dữ liệu thường được biểu diễn bằng vector số lần xuất hiện từ (Bag of Words, TF-IDF). Nhờ cách tiếp cận đó, Multinomial Naive Bayes cũng hoạt động rất hiệu quả trong các ứng dụng như phân loại tài liệu, lọc thư rác, phân tích cảm xúc hay phát hiện chủ đề.

**Bernoulli Naive Bayes:**
- Bernoulli Naive Bayes là một thuật toán phù hợp cho dữ liệu có các thuộc tính nhị phân hoặc boolean, trong đó mỗi đặc trưng chỉ nhận một trong hai giá trị như có/không, đúng/sai, được chấp nhận/bị từ chối,… Khác với Multinomial Naive Bayes, mô hình này không quan tâm số lần một đặc trưng xuất hiện mà chỉ xét đến việc nó có xuất hiện hay không.
- Trong thực tế, Bernoulli Naive Bayes đặc biệt hiệu quả với dữ liệu dạng “có/không”, chẳng hạn như việc kiểm tra từ “học” có xuất hiện trong email hay không. Mô hình này thường được áp dụng trong các bài toán phân loại văn bản ngắn, lọc thư rác hoặc những trường hợp mà sự hiện diện của đặc trưng quan trọng hơn số lần xuất hiện.

##### ***Tại sao Naive Bayes được gọi là “ngây thơ”? Giả định về tính độc lập của các đặc trưng ảnh hưởng như thế nào đến hiệu suất của mô hình?***

Naive Bayes được gọi là “ngây thơ” vì mô hình dựa trên những giả định đơn giản nhưng hiếm khi đúng trong thực tế. Cụ thể:
- Các đặc trưng (features) được coi là độc lập có điều kiện với nhau khi đã biết nhãn lớp, tức là sự thay đổi của một đặc trưng không ảnh hưởng đến các đặc trưng khác.
- Các đặc trưng được giả định có mức độ ảnh hưởng ngang nhau đến biến mục tiêu.

Trên thực tế, các đặc trưng dữ liệu thường có mối quan hệ và tương quan lẫn nhau nên giả định này hiếm khi tồn tại. Chính vì vậy, thuật toán mới được gọi là “ngây thơ”. Tuy nhiên, nhờ giả định này, việc tính toán xác suất chung được đơn giản hóa thành tích của các xác suất riêng lẻ, giúp mô hình nhẹ, dễ triển khai và dự đoán kết quả nhanh chóng.

Mặc dù mang tính “ngây thơ”, Naive Bayes vẫn hoạt động hiệu quả trong nhiều tình huống thực tế, đặc biệt trên các tập dữ liệu lớn. Các ứng dụng phổ biến có thể kể đến là lọc thư rác, phân loại văn bản, phân tích cảm xúc và dự đoán sắc thái ngôn ngữ.

Giả định về tính độc lập của các đặc trưng cũng ảnh hưởng trực tiếp đến hiệu suất của Naive Bayes. Nếu trong dữ liệu giả định này tương đối đúng, mô hình có thể dự đoán nhanh chóng và chính xác với độ phức tạp rất thấp. Ngược lại, khi các đặc trưng có mối liên hệ hoặc phụ thuộc lẫn nhau, mô hình có thể bỏ qua những thông tin quan trọng và dẫn đến phân loại sai. Dù vậy, nhờ cấu trúc đơn giản, Naive Bayes vẫn thường cho hiệu quả đáng tin cậy trong nhiều tình huống, đặc biệt khi số chiều dữ liệu lớn hoặc khi dữ liệu huấn luyện hạn chế.

##### ***Ưu điểm và hạn chế của Naive Bayes so với các thuật toán phân loại khác như SVM hoặc Random Forest là gì?***

**Ưu điểm của Naive Bayes so với SVM và Random Forest**

Naive Bayes có ưu thế nổi bật về sự đơn giản, tốc độ huấn luyện nhanh và hiệu quả cao trong các bài toán phân loại văn bản hoặc xử lý dữ liệu lớn. So với SVM, vốn yêu cầu lựa chọn và tối ưu tham số phức tạp, Naive Bayes dễ triển khai hơn nhiều và phù hợp với các tình huống cần dự đoán nhanh. Trong khi đó, so với Random Forest vốn cần nhiều tài nguyên tính toán để huấn luyện, đặc biệt là khi số lượng cây quyết định lớn. Có thể thấy, Naive Bayes nhẹ nhàng hơn và vẫn có thể cho ra kết quả đáng tin cậy trong các tập dữ liệu lớn.

**Hạn chế của Naive Bayes so với SVM và Random Forest**

Hạn chế lớn nhất của Naive Bayes là giả định tính độc lập giữa các thuộc tính, điều này hiếm khi đúng trong thực tế và có thể làm giảm độ chính xác của mô hình. Về mặt hiệu suất, SVM thường vượt trội hơn ở các không gian đặc trưng phức tạp, có khả năng phân tách tối ưu dữ liệu. Random Forest lại giảm thiểu nguy cơ overfitting nhờ sự kết hợp của nhiều cây quyết định, từ đó thường đạt được độ chính xác cao hơn Naive Bayes trong các tình huống dữ liệu phức tạp.

**Kết luận chung**

Nhìn chung, Naive Bayes là một lựa chọn tốt khi cần mô hình phân loại đơn giản, nhanh và dễ triển khai, đặc biệt trong các ứng dụng như lọc thư rác hay phân loại văn bản ngắn. Tuy nhiên, khi bài toán yêu cầu độ chính xác cao trong môi trường dữ liệu phức tạp, nhiều chiều hoặc nhiều nhiễu, SVM và Random Forest thường cho kết quả tốt hơn, dù phải đánh đổi bằng thời gian và tài nguyên tính toán.

##### ***Viết đoạn code mẫu bằng Python (sử dụng Scikit-learn) để xây dựng một mô hình Naive Bayes (ví dụ: Gaussian Naive Bayes) không? Hãy mô tả các bước thực hiện.***

**Bước 1: Import thư viện cần thiết**

In [1]:
# Bước 1: Import thư viện cần thiết
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

- load_iris: tải bộ dữ liệu mẫu Iris có sẵn trong Scikit-learn.
- train_test_split: chia dữ liệu thành hai phần (train/test).
- GaussianNB: tạo mô hình Naive Bayes với giả định các đặc trưng có phân phối chuẩn.
- accuracy_score, classification_report: dùng để đánh giá hiệu suất mô hình.

**Ý nghĩa:** Đoạn code này chuẩn bị mọi công cụ cần thiết cho quy trình huấn luyện mô hình học máy. Sau khi chạy, sẽ chưa có đầu ra vì đây mới chỉ là phần import thư viện nhưng nó là nền tảng cho toàn bộ các bước tiếp theo.

**Bước 2: Tải và chia dữ liệu**

In [2]:
# Bước 2: Tải bộ dữ liệu
iris = load_iris()
X = iris.data     # Các đặc trưng (feature)
y = iris.target   # Nhãn (label)

# Chia dữ liệu thành tập huấn luyện và kiểm tra (80% - 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

- X: chứa 4 đặc trưng — độ dài và chiều rộng của cánh và đài hoa.
- y: là nhãn tương ứng cho 3 loài hoa (Setosa, Versicolor, Virginica).
- train_test_split: chia dữ liệu thành 80% huấn luyện, 20% kiểm tra, đảm bảo đánh giá công bằng.

**Ý nghĩa:** Đoạn code này giúp tách dữ liệu để huấn luyện và đánh giá mô hình. Kết quả khi chạy sẽ không hiển thị ra màn hình, nhưng trong bộ nhớ, ta có 4 biến:
- X_train, y_train: dùng để dạy mô hình.
- X_test, y_test: dùng để kiểm tra độ chính xác của mô hình sau khi học.

**Bước 3: Khởi tạo và huấn luyện mô hình**

In [3]:
# Bước 3: Tạo mô hình Gaussian Naive Bayes
model = GaussianNB()

# Huấn luyện mô hình trên tập train
model.fit(X_train, y_train)

GaussianNB()

- GaussianNB(): tạo một mô hình Naive Bayes giả định rằng mỗi đặc trưng tuân theo phân phối chuẩn trong từng lớp.
- fit(): “dạy” mô hình — tức là ước lượng xác suất của từng lớp và tham số thống kê (trung bình, phương sai) cho từng đặc trưng.

**Ý nghĩa:** Đây là bước quan trọng nhất — mô hình bắt đầu học quy luật từ dữ liệu. Sau khi chạy, mô hình model đã sẵn sàng để dự đoán. Không có đầu ra trực tiếp, nhưng bạn có thể kiểm tra bằng:

In [4]:
print(model.class_prior_)   # Xác suất tiên nghiệm của mỗi lớp
print(model.theta_)         # Trung bình của mỗi đặc trưng theo lớp

[0.33333333 0.34166667 0.325     ]
[[4.99       3.4525     1.45       0.245     ]
 [5.9195122  2.77073171 4.24146341 1.32195122]
 [6.53333333 2.96666667 5.52051282 2.        ]]


**Bước 4: Dự đoán và đánh giá mô hình**

In [5]:
# Bước 4: Dự đoán nhãn cho tập kiểm tra
y_pred = model.predict(X_test)

# Tính độ chính xác
accuracy = accuracy_score(y_test, y_pred)

print("Độ chính xác của mô hình:", accuracy)
print("\nBáo cáo phân loại:")
print(classification_report(y_test, y_pred))

Độ chính xác của mô hình: 1.0

Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



- predict(): mô hình dựa vào công thức Bayes để chọn nhãn có xác suất hậu nghiệm cao nhất.
- accuracy_score: tính tỷ lệ dự đoán đúng trên tổng số mẫu kiểm tra.
- classification_report: hiển thị các chỉ số precision, recall, F1-score cho từng lớp.

**Ý nghĩa:** Bước này giúp đánh giá hiệu quả mô hình trên dữ liệu chưa từng thấy.

**Ý nghĩa chung:** Đoạn code này mô phỏng quy trình huấn luyện và đánh giá một mô hình học máy hoàn chỉnh:
- Chuẩn bị thư viện và dữ liệu.
- Chia dữ liệu để đảm bảo đánh giá khách quan.
- Huấn luyện mô hình Gaussian Naive Bayes dựa trên Định lý Bayes — mô hình giả định rằng các đặc trưng độc lập và có phân phối chuẩn.
- Dự đoán, đánh giá kết quả, và phân tích hiệu suất mô hình.

Đây là một ví dụ điển hình cho việc áp dụng Naive Bayes trong bài toán phân loại, minh họa cách mô hình học xác suất từ dữ liệu và đưa ra dự đoán dựa trên khả năng xảy ra của từng lớp.

##### ***Làm thế nào để xử lý dữ liệu phân loại (categorical data) trước khi áp dụng Multinomial Naive Bayes trong Python?***

Để có thể áp dụng Multinomial Naive Bayes cho dữ liệu phân loại trong Python, yêu cầu quan trọng nhất là chuyển đổi toàn bộ dữ liệu về dạng số nguyên không âm. Nguyên nhân là vì mô hình này được xây dựng dựa trên giả định về tần suất hoặc số lần xuất hiện của đặc trưng nên dữ liệu cần được biểu diễn dưới dạng rời rạc, thay vì ở dạng chuỗi hoặc nhãn phân loại thô.

Trong trường hợp dữ liệu là văn bản, các kỹ thuật phổ biến như CountVectorizer hoặc TfidfVectorizer thường được sử dụng để biến đổi từ ngữ thành vector đặc trưng. Còn đối với dữ liệu phân loại rời rạc (chẳng hạn như màu sắc, kích thước, giới tính…), các phương pháp mã hóa như OneHotEncoder giúp biểu diễn từng giá trị dưới dạng vector nhị phân, hoặc LabelEncoder được áp dụng khi cột có ít giá trị và không cần phân biệt mức độ thứ tự. Những cách tiếp cận này đảm bảo dữ liệu sau khi xử lý phù hợp với yêu cầu toán học của Multinomial Naive Bayes.

Sau khi đã mã hóa và loại bỏ khả năng xuất hiện giá trị âm, dữ liệu có thể được đưa trực tiếp vào mô hình MultinomialNB để huấn luyện và dự đoán. Như vậy, việc xử lý dữ liệu phân loại trước khi áp dụng Multinomial Naive Bayes thực chất là quá trình mã hóa dữ liệu về dạng số rời rạc, nhằm đáp ứng giả định nền tảng của thuật toán và đảm bảo kết quả phân loại đạt độ tin cậy cao.

##### ***Naive Bayes thường được sử dụng trong phân loại văn bản (text classification). Bạn có thể giải thích cách triển khai Naive Bayes cho bài toán này không?***

**Bước 0: Import các thư viện cần thiết**

In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

- CountVectorizer và TfidfVectorizer dùng để biến văn bản thành ma trận số.
- MultinomialNB là mô hình Naive Bayes phù hợp với dữ liệu đếm từ.
- train_test_split dùng để chia dữ liệu thành tập huấn luyện và tập kiểm tra.
- accuracy_score để đánh giá mức độ chính xác của mô hình.

**Bước 1: Chuẩn bị dữ liệu**

Trước hết, cần có dữ liệu văn bản kèm nhãn (ví dụ: cảm xúc Positive/Negative).

In [3]:
# Dữ liệu ví dụ
corpus = [
    "I love this movie",
    "This movie is amazing",
    "I hate this movie",
    "This movie is terrible"
]
labels = ["Positive", "Positive", "Negative", "Negative"]

- corpus là danh sách các câu văn bản mà chúng ta muốn phân loại.
- labels là nhãn tương ứng cho từng câu, dùng làm dữ liệu huấn luyện.
- Đây là bước bắt buộc vì Naive Bayes cần cả văn bản và nhãn để học phân phối xác suất.

**Bước 2: Chuyển văn bản thành ma trận số**

Naive Bayes không thể xử lý chữ trực tiếp, cần biến văn bản thành số nguyên không âm (số lần mỗi từ xuất hiện) bằng Bag of Words.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

# Tạo ma trận đếm từ
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Ma trận đếm từ:\n", X.toarray())
print("Từ vựng:\n", vectorizer.get_feature_names_out())

Ma trận đếm từ:
 [[0 0 0 1 1 0 1]
 [1 0 1 0 1 0 1]
 [0 1 0 0 1 0 1]
 [0 0 1 0 1 1 1]]
Từ vựng:
 ['amazing' 'hate' 'is' 'love' 'movie' 'terrible' 'this']


- CountVectorizer biến mỗi câu thành một vector số nguyên, mỗi phần tử là số lần từ đó xuất hiện trong câu.
- fit_transform vừa học từ vựng từ tập dữ liệu, vừa tạo ma trận đặc trưng cho mô hình.
- Mục đích: đưa dữ liệu văn bản về dạng số, phù hợp cho Multinomial Naive Bayes.

**Bước 3: Huấn luyện mô hình Naive Bayes**

Dùng MultinomialNB vì dữ liệu là đếm từ (không âm).

In [6]:
from sklearn.naive_bayes import MultinomialNB

# Khởi tạo và huấn luyện mô hình
model = MultinomialNB()
model.fit(X, labels)

MultinomialNB()

- MultinomialNB tính xác suất mỗi từ xuất hiện trong từng lớp (Positive/Negative).
- fit dùng ma trận từ (X) và nhãn (labels) để học mô hình.
- Mục đích: mô hình học phân phối xác suất của từ trong từng lớp, để sau này dự đoán nhãn cho văn bản mới.

**Bước 4: Dự đoán nhãn cho văn bản mới**

Sau khi huấn luyện, có thể dự đoán nhãn cho câu chưa biết.

In [7]:
# Câu mới cần dự đoán
test = ["I love this amazing movie"]
X_test = vectorizer.transform(test)
pred = model.predict(X_test)
print("Dự đoán:", pred)

Dự đoán: ['Positive']


- transform chuyển câu mới sang vector số, sử dụng từ vựng đã học từ CountVectorizer.
- predict dự đoán nhãn dựa trên xác suất từ đã học.
- Mục đích: áp dụng mô hình đã học để phân loại văn bản mới.

**Bước 5: Đánh giá mô hình**

Kiểm tra hiệu quả mô hình trên tập huấn luyện hoặc tập test.

In [9]:
from sklearn.metrics import accuracy_score

# Dự đoán trên tập huấn luyện
y_pred = model.predict(X)
print("Accuracy:", accuracy_score(labels, y_pred))

Accuracy: 1.0


- accuracy_score tính tỷ lệ dự đoán đúng.
- Mục đích: đánh giá mức độ chính xác của mô hình.
- Lưu ý: với dữ liệu thực tế, nên chia train/test để tránh đánh giá sai do overfitting.

**Bước 6 (tùy chọn): Dùng TF-IDF thay vì đếm từ**

TF-IDF giảm trọng số các từ phổ biến, tăng trọng số từ quan trọng, cải thiện hiệu quả.

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus)
model.fit(X_tfidf, labels)

# Dự đoán với TF-IDF
X_test_tfidf = tfidf.transform(test)
pred_tfidf = model.predict(X_test_tfidf)
print("Dự đoán với TF-IDF:", pred_tfidf)

Dự đoán với TF-IDF: ['Positive']


- TfidfVectorizer chuyển văn bản thành ma trận trọng số, không chỉ đếm số lần từ xuất hiện.
- Mục đích: làm nổi bật từ quan trọng, giảm ảnh hưởng từ thông dụng, giúp phân loại chính xác hơn.

#### **2.3.2. Bài làm mẫu**

##### **Bài toán 1:** Xây dựng mô hình dữ liệu bằng giải thuật Bayes ngây thơ trên tập dữ liệu lấy tại https://www.kaggle.com/code/zabihullah18/email-spam-detection

##### **Nhiệm vụ 1: Phân loại sử dụng Naïve Bays**

1. Import thư viện và nạp dữ liệu vào notebook

In [15]:
#Importing the Necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
data = pd.read_csv('./datasets/spam.csv', encoding='latin-1')
#display the first 5 rows
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

2. Xử lý dữ liệu trước khi xây dựng mô hình từ dữ liệu

In [8]:
# Drop the columns with NaN values
data = data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)
# Rename columns for clarity:
data.columns = ['label', 'text']
# Separate features (X) and target labels (y)
X = data.drop('label', axis=1)
y = data['label']
# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

3. Xây dựng vector hóa nội dung HAM | SPAM của tập train và tập test

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
# Fit and transform the training data (X_train)
X_train_vectorized = vectorizer.fit_transform(X_train['text'])
# Transform the test data (X_test)
X_test_vectorized = vectorizer.transform(X_test['text'])

4. Xây dựng mô hình Naïve Bayes

In [10]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)


MultinomialNB()

5. Đánh giá hiệu quả của mô hình

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Make predictions on the test data
y_pred = classifier.predict(X_test_vectorized)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.98
Confusion Matrix:
[[963   2]
 [ 16 134]]
Classification Report:
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.94       150

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



#### **2.3.3. Bài tập thực hành 1**

Xây dựng mô hình Naïve ngây thơ trên tập dữ liệu hành vi của khách hàng lấy tại
https://www.kaggle.com/code/arezalo/customer-behaviour-prediction-naive-bayes

In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
data = pd.read_csv('./datasets/Customer_Behaviour.csv', encoding='latin-1')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [12]:
# Drop unnecessary columns
data = data.drop(columns=['User ID'], axis=1)

# Rename categorical column and convert to numeric
data['Gender'] = data['Gender'].map({'Male': 0, 'Female': 1})

# Separate features (X) and target labels (y)
X = data.drop('Purchased', axis=1)
y = data['Purchased']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit and transform the training data (X_train)
X_train_scaled = scaler.fit_transform(X_train)
# Transform the test data (X_test)
X_test_scaled = scaler.transform(X_test)

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
# Fit the model on the training data
classifier.fit(X_train, y_train)

GaussianNB()

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

# Make predictions on the test data
y_pred = classifier.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, zero_division=0)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.65
Confusion Matrix:
[[52  0]
 [28  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.65      1.00      0.79        52
           1       0.00      0.00      0.00        28

    accuracy                           0.65        80
   macro avg       0.33      0.50      0.39        80
weighted avg       0.42      0.65      0.51        80



#### **2.3.3. Bài tập thực hành 2**

Xây dựng mô hình Naïve ngây thơ trên tập dữ liệu mushroom. Dữ liệu lấy tại
https://www.kaggle.com/datasets/uciml/mushroom-classification/data

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
data = pd.read_csv('./datasets/mushrooms.csv', encoding='latin-1')
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
data = pd.get_dummies(data, drop_first=True)
# Separate features (X) and target labels (y)
X = data.drop('class_p', axis=1)
y = data['class_p']
# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
from sklearn.preprocessing import StandardScaler
data = pd.get_dummies(data, drop_first=True)

# Separate features (X) and target labels (y)
X = data.drop('class_p', axis=1)
y = data['class_p']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [6]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Make predictions on the test data
y_pred = classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.95
Confusion Matrix:
[[835   8]
 [ 71 711]]
Classification Report:
              precision    recall  f1-score   support

       False       0.92      0.99      0.95       843
        True       0.99      0.91      0.95       782

    accuracy                           0.95      1625
   macro avg       0.96      0.95      0.95      1625
weighted avg       0.95      0.95      0.95      1625



## **KẾT THÚC GIẢI THUẬT 3**